### ISSUE TITLE
encoding problem when the script is run under Windows

### ISSUE THREAD

**Issue by eroux** [buda-base/convert-2-outline-xml#1]
(from NT) under Windows, the script produces xml where all unicode characters are encoded as entities. I have no example of that yet, but maybe NT will upload one

**Comment by jeehuajian** [comment]
**Input file**
![input](https://user-images.githubusercontent.com/42564256/62189494-af14e700-b3a1-11e9-80f0-d490109a6e1f.PNG)

**Output file**
![output](https://user-images.githubusercontent.com/42564256/62189506-b805b880-b3a1-11e9-8b85-3e5aeb4e0f02.PNG)

**CMD Command**
C:\Users\drong\java -jar C:\Users\drong\Desktop\outline\convert-2-outline-xml-1.8.1.jar -docdir C:\Users\drong\Desktop\outline\Input\ -outdir C:\Users\drong\Desktop\outline\Output -who Lobsang -title ""

**Comment by xristy** [comment]
those aren't xml entities. Either the tool isn't outputting UTF-8 or the application that was used to view the output file didn't open using UTF-8.

@jeehuajian please add the output file to the issue

**Comment by eroux** [comment]
please also add the input file (to check if it's utf16)

**Comment by xristy** [comment]
@jeehuajian I don't know that this is related but it is at least another example of encoding issues. The following are four commit messages for the [buda-base/embedded-reader-import]:

![Screen Shot 2019-08-01 at 9 50 35 AM](https://user-images.githubusercontent.com/3542294/62303725-40d43100-b442-11e9-8213-68b7e14b0456.png)

The raw message contents:

> Subject: =?utf-8?q?=5Bbuda-base/embedded-reader-import=5D_3d3fc24=3A_?=
 =?utf-8?b?w6DCvcKWw6DCvcKfw6DCvcK8w6DCvMKLw6DCvcKWw6DCvcKew6DCvcKyw6A=?=
 =?utf-8?b?wr3Ck8OgwrzCi8Ogwr3CocOgwr3CvMOgwr3CkcOgwrzCjQ==?=

indicate that the encoding being sent is utf-8; however, it's the same sort of encoding mismatch as indicated in this issue above.

Hopefully once we see the original input csv, and the xlsx, and the output files of the converter then we'll be able to diagnose.

Also please let us know what O/S and version and Java version you are running the converter on.

**Comment by ngawangtrinley** [comment]
Here are the files. Lobsang will tell us more about his system.
https://github.com/buda-base/convert-2-outline-xml/tree/master/test

**Comment by jeehuajian** [comment]
**Window** 
![Window version](https://user-images.githubusercontent.com/42564256/62354740-22ecf600-b540-11e9-9055-39ef3bcd5b54.PNG)

**Java**
![Java](https://user-images.githubusercontent.com/42564256/62354794-35672f80-b540-11e9-9a54-a176e5b0d4fa.PNG)

**Comment by eroux** [comment]
Thanks! Interesting, these are both UTF8 files... I can't really test right now but we might be missing some `"UTF-8"` argument in file opening... although I can't see a place where it's missing...

**Comment by xristy** [comment]
Use v1.8.3. The problem was that the converter was using the system default which on Windows 10 is still cp1252. The converter now sets the encoding to UTF-8 when reading the csv - which must be in UTF-8.
