### ISSUE TITLE
Outlines that do are found from Work

### ISSUE THREAD

**Issue by xristy** [buda-base/convert-2-outline-xml#6]
Converted outlines don't get found from the tbrc.org UI. 

For example [W1KG4185](https://www.tbrc.org/#!rid=W1KG4185) now has the converted Outline [O1KG4185](https://www.tbrc.org/xmldoc?rid=O1KG4185) but it doesn't appear when visiting [W1KG4185](https://www.tbrc.org/#!rid=W1KG4185) as it should. It [can be seen](https://www.tbrc.org/#!rid=O1KG4185) but not as it is supposed to.

**Comment by eroux** [comment]
@xristy I think that's because of the `status="provisional"`, should we change it to `released` in the converter?
